$(function(){"use strict";var window_width=$(window).width();$(window).load(function(){setTimeout(function(){$('body').addClass('loaded');},200);});$('.show-search').click(function(){$('.search-out').fadeToggle("50","linear");});$('#task-card input:checkbox').each(function(){checkbox_check(this);});$('#task-card input:checkbox').change(function(){checkbox_check(this);});function checkbox_check(el){if(!$(el).is(':checked')){$(el).next().css('text-decoration','none');}else{$(el).next().css('text-decoration','line-through');}}
$('.slider').slider({full_width:true});$('.dropdown-button').dropdown({inDuration:300,outDuration:125,constrain_width:true,hover:false,alignment:'left',gutter:0,belowOrigin:true});$('.tab-demo').show().tabs();$('.tab-demo-active').show().tabs();$('.parallax').parallax();$('.modal-trigger').leanModal();$('.scrollspy').scrollSpy();$('.tooltipped').tooltip({delay:50});$('.sidebar-collapse').sideNav({edge:'left',});$('.chat-collapse').sideNav({menuWidth:240,edge:'right',});$('.chat-close-collapse').click(function(){$('.chat-collapse').sideNav('hide');});$('.chat-collapsible').collapsible({accordion:false});$('.datepicker').pickadate({selectMonths:true,selectYears:15});$('select').not('.disabled').material_select();var leftnav=$(".page-topbar").height();var leftnavHeight=window.innerHeight-leftnav;$('.leftside-navigation').height(leftnavHeight).perfectScrollbar({suppressScrollX:true});var righttnav=$("#chat-out").height();$('.rightside-navigation').height(righttnav).perfectScrollbar({suppressScrollX:true});function toggleFullScreen(){if((document.fullScreenElement&&document.fullScreenElement!==null)||(!document.mozFullScreen&&!document.webkitIsFullScreen)){if(document.documentElement.requestFullScreen){document.documentElement.requestFullScreen();}
else if(document.documentElement.mozRequestFullScreen){document.documentElement.mozRequestFullScreen();}
else if(document.documentElement.webkitRequestFullScreen){document.documentElement.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);}}
else{if(document.cancelFullScreen){document.cancelFullScreen();}
else if(document.mozCancelFullScreen){document.mozCancelFullScreen();}
else if(document.webkitCancelFullScreen){document.webkitCancelFullScreen();}}}
$('.toggle-fullscreen').click(function(){toggleFullScreen();});if($('nav').length){$('.toc-wrapper').pushpin({top:$('nav').height()});}
else if($('#index-banner').length){$('.toc-wrapper').pushpin({top:$('#index-banner').height()});}
else{$('.toc-wrapper').pushpin({top:0});}
var toggleFlowTextButton=$('#flow-toggle')
toggleFlowTextButton.click(function(){$('#flow-text-demo').children('p').each(function(){$(this).toggleClass('flow-text');})});var toggleContainersButton=$('#container-toggle-button');toggleContainersButton.click(function(){$('body .browser-window .container, .had-container').each(function(){$(this).toggleClass('had-container');$(this).toggleClass('container');if($(this).hasClass('container')){toggleContainersButton.text("Turn off Containers");}
else{toggleContainersButton.text("Turn on Containers");}});});function is_touch_device(){try{document.createEvent("TouchEvent");return true;}
catch(e){return false;}}
if(is_touch_device()){$('#nav-mobile').css({overflow:'auto'})}
new Chartist.Line('#ct2-chart',{labels:[1,2,3,4,5,6,7,8],series:[[5,9,7,8,5,3,5,4]]},{low:0,showArea:true});if(window_width<=480){$("#trending-line-chart").attr({height:'200'});}});